#!/usr/bin/env node
/**
 * Codex Nexus local aggregation gateway.
 *
 * The gateway intentionally uses Node's standard library so it can run as a
 * small sidecar in development and in a bundled desktop release. Provider
 * credentials are loaded from a local manifest generated by the Rust control
 * plane; request/response bodies are never written to logs.
 */
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

const HOST = process.env.CODEX_NEXUS_HOST || '127.0.0.1';
const PORT = Number(process.env.CODEX_NEXUS_PORT || 0);
const CONFIG_PATH = process.env.CODEX_NEXUS_CONFIG || path.join(process.env.CODEX_NEXUS_DATA || '.', 'gateway.json');
const MAX_BODY = 8 * 1024 * 1024;
const sessionRoutes = new Map();
const cooldowns = new Map();
const rotation = new Map();
let config = { providers: [], accounts: [], pools: [], apiKeys: [] };

const json = (res, status, value, headers = {}) => {
  const body = JSON.stringify(value);
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'content-length': Buffer.byteLength(body), ...headers });
  res.end(body);
};

const error = (res, status, code, message, details = {}) => json(res, status, { error: { code, message, ...details } });

async function loadConfig() {
  try {
    const raw = await fs.readFile(CONFIG_PATH, 'utf8');
    config = { ...config, ...JSON.parse(raw) };
  } catch (err) {
    if (err.code !== 'ENOENT') console.error(`[gateway] configuration error: ${err.message}`);
  }
}

async function readBody(req) {
  const chunks = [];
  let size = 0;
  for await (const chunk of req) {
    size += chunk.length;
    if (size > MAX_BODY) throw Object.assign(new Error('request body too large'), { statusCode: 413 });
    chunks.push(chunk);
  }
  return Buffer.concat(chunks);
}

function authAllowed(req) {
  const presented = req.headers.authorization?.replace(/^Bearer\s+/i, '') || req.headers['x-api-key'];
  const keys = config.apiKeys || [];
  return keys.length === 0 || keys.some((key) => key.enabled !== false && key.key === presented);
}

function findApiKey(req) {
  const presented = req.headers.authorization?.replace(/^Bearer\s+/i, '') || req.headers['x-api-key'];
  return (config.apiKeys || []).find((key) => key.enabled !== false && key.key === presented);
}

function routeFromModel(model) {
  const routes = config.routes || [];
  if (model?.includes('/')) {
    const [namespace, ...rest] = model.split('/');
    const route = routes.find((item) => item.namespace === namespace && item.enabled !== false);
    if (!route) return { error: 'model_route_not_available', message: `Unknown or disabled model namespace: ${namespace}` };
    const upstreamModel = rest.join('/');
    if (route.models?.length && !route.models.includes(upstreamModel) && !route.upstreamModels?.includes(upstreamModel)) {
      return { error: 'model_route_not_available', message: `Model ${model} is not enabled in namespace ${namespace}` };
    }
    return { route, upstreamModel, clientModel: model };
  }
  const defaultRoute = routes.find((item) => item.default === true && item.enabled !== false) || routes.find((item) => item.enabled !== false);
  if (!defaultRoute) return { error: 'model_route_not_available', message: 'No default provider route is configured' };
  return { route: defaultRoute, upstreamModel: model, clientModel: model };
}

function eligibleAccounts(route, apiKey, excluded = new Set()) {
  const requested = apiKey?.accountIds || route.accountIds;
  const ids = requested?.length ? new Set(requested) : null;
  const now = Date.now();
  return (config.accounts || []).filter((account) => {
    if (account.enabled === false || excluded.has(account.id) || (ids && !ids.has(account.id))) return false;
    if (account.providerId !== route.providerId) return false;
    if (account.expiresAt && Date.parse(account.expiresAt) <= now) return false;
    if ((account.quotaRemaining ?? 1) <= 0) return false;
    const cooldownUntil = cooldowns.get(account.id) || 0;
    return cooldownUntil <= now;
  });
}

function chooseAccount(route, apiKey, sessionId, image = false, excluded = new Set()) {
  const candidates = eligibleAccounts(route, apiKey, excluded);
  if (!candidates.length) return { error: 'auth_unavailable', message: `No healthy account is available for ${route.namespace}` };
  const affinityKey = image ? null : sessionId;
  if (affinityKey) {
    const bound = sessionRoutes.get(affinityKey);
    const match = candidates.find((account) => account.id === bound);
    if (match) return match;
  }
  const policy = apiKey?.routingStrategy || route.routingStrategy || 'quota-aware';
  const sorted = [...candidates].sort((a, b) => {
    if (policy === 'priority') return (b.priority || 0) - (a.priority || 0);
    if (policy === 'expiry-soon-first') return Date.parse(a.expiresAt || '9999-12-31') - Date.parse(b.expiresAt || '9999-12-31');
    return (b.quotaRemaining ?? 1) - (a.quotaRemaining ?? 1) || (b.priority || 0) - (a.priority || 0);
  });
  let chosen = sorted[0];
  if (policy === 'random') chosen = sorted[crypto.randomInt(sorted.length)];
  if (policy === 'round-robin' || policy === 'weighted') {
    const key = `${route.namespace}:${apiKey?.id || 'default'}`;
    const index = rotation.get(key) || 0;
    chosen = sorted[index % sorted.length];
    rotation.set(key, index + 1);
  }
  if (affinityKey) sessionRoutes.set(affinityKey, chosen.id);
  return chosen;
}

function endpointFor(route, kind) {
  const base = String(route.baseUrl || '').replace(/\/$/, '');
  const endpoint = route.endpoints?.[kind] || (kind === 'responses' ? '/v1/responses' : kind === 'chat' ? '/v1/chat/completions' : `/v1/images/${kind}`);
  return `${base}${endpoint.startsWith('/') ? endpoint : `/${endpoint}`}`;
}

function providerHeaders(route, account) {
  const headers = { 'content-type': 'application/json', ...(route.headers || {}) };
  if (account?.apiKey) headers.authorization = `Bearer ${account.apiKey}`;
  return headers;
}

async function upstreamRequest(route, account, kind, body, stream) {
  const response = await fetch(endpointFor(route, kind), {
    method: 'POST',
    headers: providerHeaders(route, account),
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(Number(route.timeoutMs || 120000)),
  });
  return response;
}

function writeMetadata(req, route, account, clientModel, upstreamModel, status) {
  console.log(JSON.stringify({ at: new Date().toISOString(), method: req.method, path: req.url, routeKind: route.protocol || 'openai', routeId: route.id, accountId: account.id, clientModel, upstreamModel, status }));
}

function models() {
  return (config.routes || []).filter((route) => route.enabled !== false).flatMap((route) => {
    const names = route.models || route.upstreamModels || [];
    return names.map((model) => ({ id: route.namespace ? `${route.namespace}/${model}` : model, object: 'model', owned_by: route.providerId }));
  });
}

async function handleModelRequest(req, res, kind) {
  let body;
  try { body = JSON.parse((await readBody(req)).toString('utf8') || '{}'); } catch { return error(res, 400, 'invalid_json', 'Request body must be valid JSON'); }
  const apiKey = findApiKey(req);
  const model = body.model;
  if (apiKey?.allowedModels?.length && !apiKey.allowedModels.includes(model)) return error(res, 403, 'model_not_allowed', `Model ${model} is not enabled for this API key`);
  const target = routeFromModel(model);
  if (target.error) return error(res, 404, target.error, target.message);
  if (apiKey?.routeNamespaces?.length && !apiKey.routeNamespaces.includes(target.route.namespace)) return error(res, 403, 'route_not_allowed', 'This API key cannot use the selected provider route');
  const outgoing = { ...body, model: target.upstreamModel };
  const isStream = body.stream === true;
  const excluded = new Set();
  const maxAttempts = Math.max(1, Math.min(5, Number(target.route.maxRetries ?? 2) + 1));
  let lastError = 'No healthy account is available';
  for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
    const account = chooseAccount(target.route, apiKey, req.headers['x-codex-session-id'] || body.metadata?.session_id, kind.startsWith('image'), excluded);
    if (account.error) return error(res, 503, account.error, account.message);
    try {
      const upstream = await upstreamRequest(target.route, account, kind, outgoing, isStream);
      writeMetadata(req, target.route, account, target.clientModel, target.upstreamModel, upstream.status);
      if (upstream.ok) {
        res.writeHead(upstream.status, Object.fromEntries(upstream.headers.entries()));
        if (upstream.body) for await (const chunk of upstream.body) res.write(chunk);
        return res.end();
      }
      lastError = `upstream returned ${upstream.status}`;
      if (upstream.status < 500 || attempt === maxAttempts) {
        const text = await upstream.text();
        return json(res, upstream.status, { error: { code: 'upstream_error', message: text.slice(0, 2000), routeId: target.route.id } });
      }
      cooldowns.set(account.id, Date.now() + Number(target.route.cooldownMs || 15000));
      excluded.add(account.id);
    } catch (err) {
      lastError = err.message;
      cooldowns.set(account.id, Date.now() + Number(target.route.cooldownMs || 15000));
      excluded.add(account.id);
      writeMetadata(req, target.route, account, target.clientModel, target.upstreamModel, 502);
      if (attempt === maxAttempts) return error(res, 502, 'upstream_unreachable', lastError);
    }
  }
  return error(res, 503, 'auth_unavailable', lastError);
}

const server = http.createServer(async (req, res) => {
  try {
    if (req.method === 'GET' && req.url === '/health') return json(res, 200, { ok: true, service: 'codex-nexus-gateway', routes: (config.routes || []).length });
    if (!authAllowed(req)) return error(res, 401, 'invalid_api_key', 'A valid local gateway API key is required');
    if (req.method === 'GET' && req.url === '/v1/models') return json(res, 200, { object: 'list', data: models() });
    if (req.method === 'POST' && req.url === '/v1/responses') return handleModelRequest(req, res, 'responses');
    if (req.method === 'POST' && req.url === '/v1/chat/completions') return handleModelRequest(req, res, 'chat');
    if (req.method === 'POST' && req.url === '/v1/images/generations') return handleModelRequest(req, res, 'generations');
    if (req.method === 'POST' && req.url === '/v1/images/edits') return handleModelRequest(req, res, 'edits');
    return error(res, 404, 'not_found', 'Route not found');
  } catch (err) {
    return error(res, err.statusCode || 500, 'gateway_error', err.message);
  }
});

await loadConfig();
server.listen(PORT, HOST, () => {
  const address = server.address();
  console.log(JSON.stringify({ ready: true, host: HOST, port: address.port, config: CONFIG_PATH }));
});

process.on('SIGTERM', () => server.close(() => process.exit(0)));
process.on('SIGINT', () => server.close(() => process.exit(0)));
