import { StrictMode, useState } from 'react';
import type { ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Activity, Archive, ArrowUpRight, Check, ChevronRight, CircleHelp, Clock3,
  Cloud, Code2, Database, FolderOpen, Gauge, HardDrive, Image, KeyRound,
  LayoutDashboard, Library, ListFilter, LockKeyhole, Menu, MessageSquare,
  MoreHorizontal, Package, PanelLeftClose, Plus, PlugZap, RefreshCw,
  Search, Settings2, ShieldCheck, Sparkles, Trash2, UserRound, Waypoints,
  X, Zap,
} from 'lucide-react';
import './styles.css';

type PageId = 'overview' | 'providers' | 'pools' | 'conversations' | 'storage' | 'skills' | 'prompts' | 'mcp' | 'images' | 'settings';

type Provider = { id: string; name: string; protocol: string; endpoint: string; models: number; status: '正常' | '需要处理'; accent: string };
type Account = { id: string; name: string; provider: string; plan: string; quota: number; status: '可用' | '冷却中'; color: string };
type Artifact = { id: string; name: string; path: string; size: string; kind: string; session: string; selected: boolean };

const navGroups = [
  { label: '工作区', items: [
    { id: 'overview' as PageId, label: '总览', icon: LayoutDashboard },
    { id: 'conversations' as PageId, label: '历史会话', icon: MessageSquare, badge: '12' },
    { id: 'storage' as PageId, label: '文件清理', icon: HardDrive, badge: '2.4 GB' },
  ] },
  { label: '控制中心', items: [
    { id: 'providers' as PageId, label: '供应商', icon: Waypoints },
    { id: 'pools' as PageId, label: '账号池', icon: UserRound },
    { id: 'images' as PageId, label: '生图工作台', icon: Image, badge: 'MCP' },
  ] },
  { label: '扩展能力', items: [
    { id: 'skills' as PageId, label: '技能', icon: Sparkles },
    { id: 'prompts' as PageId, label: '提示词', icon: Library },
    { id: 'mcp' as PageId, label: 'MCP 服务', icon: PlugZap },
  ] },
];

const initialProviders: Provider[] = [
  { id: 'openai-subscription', name: 'Codex 订阅账号', protocol: 'OAuth · Responses', endpoint: 'app-server://local', models: 7, status: '正常', accent: 'violet' },
  { id: 'openrouter', name: 'OpenRouter', protocol: 'OpenAI 兼容协议', endpoint: 'https://openrouter.ai/api/v1', models: 42, status: '正常', accent: 'cyan' },
  { id: 'anthropic', name: 'Anthropic', protocol: 'Messages API', endpoint: 'https://api.anthropic.com', models: 5, status: '需要处理', accent: 'orange' },
];

const initialAccounts: Account[] = [
  { id: 'acct-codex', name: 'personal@codex', provider: 'Codex 订阅账号', plan: 'Plus · 周配额', quota: 82, status: '可用', color: 'violet' },
  { id: 'acct-openrouter', name: 'OpenRouter 密钥', provider: 'OpenRouter', plan: 'API · 聚合池', quota: 64, status: '可用', color: 'cyan' },
  { id: 'acct-anthropic', name: 'team-api', provider: 'Anthropic', plan: 'API · 备用路由', quota: 31, status: '冷却中', color: 'orange' },
];

const initialArtifacts: Artifact[] = [
  { id: 'a1', name: 'concept-board.png', path: '~/项目/nexus/.codex/artifacts/concept-board.png', size: '1.2 GB', kind: 'Image', session: '品牌探索', selected: false },
  { id: 'a2', name: 'benchmarks.json', path: '~/项目/nexus/.codex/artifacts/benchmarks.json', size: '684 MB', kind: '数据', session: '供应商基准测试', selected: false },
  { id: 'a3', name: 'landing-preview.webp', path: '~/项目/nexus/.codex/artifacts/landing-preview.webp', size: '421 MB', kind: 'Image', session: '落地页设计', selected: false },
  { id: 'a4', name: 'notes.md', path: '~/项目/nexus/.codex/artifacts/notes.md', size: '92 KB', kind: 'Text', session: '工作区重构', selected: false },
];

function App() {
  const [active, setActive] = useState<PageId>('overview');
  const [providers, setProviders] = useState(initialProviders);
  const [accounts, setAccounts] = useState(initialAccounts);
  const [artifacts, setArtifacts] = useState(initialArtifacts);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [search, setSearch] = useState('');
  const [toast, setToast] = useState('');

  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400); };
  const selectedArtifacts = artifacts.filter((artifact) => artifact.selected);
  const storageTotal = selectedArtifacts.length ? selectedArtifacts.length === artifacts.length ? '2.4 GB' : `${selectedArtifacts.length} 已选择` : '2.4 GB';

  const toggleArtifact = (id: string) => setArtifacts((items) => items.map((item) => item.id === id ? { ...item, selected: !item.selected } : item));
  const quarantineSelected = () => {
    if (!selectedArtifacts.length) return notify('请先选择要移入可恢复隔离区的文件');
    setArtifacts((items) => items.filter((item) => !item.selected));
    notify(`${selectedArtifacts.length} 个文件已移入隔离区`);
  };

  return <div className="app-shell">
    {sidebarOpen && <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Zap size={17} fill="currentColor" /></div><div><strong>Codex Nexus</strong><span>本地控制中心</span></div></div>
      <div className="profile-chip"><div className="avatar">DL</div><div><strong>DearLicy</strong><span>个人工作区</span></div><ChevronRight size={15} /></div>
      <nav>{navGroups.map((group) => <div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map((item) => { const Icon = item.icon; return <button key={item.id} className={`nav-item ${active === item.id ? 'active' : ''}`} onClick={() => setActive(item.id)}><Icon size={17} /><span>{item.label}</span>{item.badge && <em>{item.badge}</em>}</button>; })}</div>)}</nav>
      <div className="sidebar-bottom"><div className="gateway-state"><span className="online-dot" /><div><strong>网关运行中</strong><span>127.0.0.1 · 8787</span></div><Activity size={15} /></div><button className="nav-item" onClick={() => setActive('settings')}><Settings2 size={17} /><span>设置</span></button></div>
    </aside>}
    <main className={`main ${sidebarOpen ? '' : 'expanded'}`}>
      <header className="topbar"><button className="icon-btn" onClick={() => setSidebarOpen((open) => !open)} aria-label="切换侧栏">{sidebarOpen ? <PanelLeftClose size={18} /> : <Menu size={18} />}</button><div className="breadcrumbs"><span>Codex Nexus</span><ChevronRight size={14} /><strong>{navGroups.flatMap((g) => g.items).find((i) => i.id === active)?.label || '总览'}</strong></div><div className="top-actions"><div className="search"><Search size={15} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜索工作区" /><kbd>⌘ K</kbd></div><button className="icon-btn"><CircleHelp size={18} /></button><div className="top-avatar">DL</div></div></header>
      <div className="page-wrap">{active === 'overview' && <Overview providers={providers} accounts={accounts} artifacts={artifacts} setActive={setActive} notify={notify} />}{active === 'providers' && <Providers providers={providers} setProviders={setProviders} notify={notify} />}{active === 'pools' && <Pools accounts={accounts} notify={notify} />}{active === 'conversations' && <Conversations notify={notify} />}{active === 'storage' && <Storage artifacts={artifacts} storageTotal={storageTotal} toggleArtifact={toggleArtifact} quarantineSelected={quarantineSelected} notify={notify} />}{active === 'images' && <ImageLab notify={notify} />}{active === 'skills' && <ExtensionPage kind="Skills" icon={Sparkles} accent="violet" notify={notify} />}{active === 'prompts' && <ExtensionPage kind="Prompts" icon={Library} accent="cyan" notify={notify} />}{active === 'mcp' && <McpPage notify={notify} />}{active === 'settings' && <SettingsPage notify={notify} />}</div>
    </main>
    {toast && <div className="toast"><Check size={16} />{toast}</div>}
  </div>;
}

function PageHeader({ eyebrow, title, description, action, onAction }: { eyebrow: string; title: string; description: string; action?: string; onAction?: () => void }) {
  return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action && <button className="primary-btn" onClick={onAction}><Plus size={16} />{action}</button>}</div>;
}

function Overview({ providers, accounts, artifacts, setActive, notify }: { providers: Provider[]; accounts: Account[]; artifacts: Artifact[]; setActive: (id: PageId) => void; notify: (msg: string) => void }) {
  return <><PageHeader eyebrow="2026年10月8日 · 星期三" title="早上好，DearLicy" description="Codex 控制中心运行正常。上下文、路由与文件都在本机清晰可见。" action="连接供应商" onAction={() => setActive('providers')} /><div className="hero-grid"><div className="hero-card gradient-violet"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-content"><div className="pill"><span className="pulse" />全部系统正常</div><h2>一个清晰的地方<br />管理所有 Codex 路由。</h2><p>账号、供应商、会话和生成文件留在本机，随时可检查。</p><button className="ghost-light" onClick={() => setActive('pools')}>打开账号池 <ArrowUpRight size={15} /></button></div><div className="hero-metric"><span>今日用量</span><strong>68.4k</strong><small>令牌 · 来自 3 条路由</small></div></div><div className="quick-card"><div className="section-kicker">快捷操作</div><QuickAction icon={Waypoints} label="配置供应商" detail="添加 API 或 OAuth" onClick={() => setActive('providers')} /><QuickAction icon={Image} label="生成图片" detail="原生注入或 MCP 回退" onClick={() => setActive('images')} /><QuickAction icon={HardDrive} label="查看文件占用" detail="2.4 GB 可释放" onClick={() => setActive('storage')} /></div></div><div className="stat-grid"><Stat label="活跃供应商" value={providers.length.toString()} sub="2 种协议类型" icon={Waypoints} tone="violet" /><Stat label="池内账号" value={accounts.length.toString()} sub="1 个冷却中" icon={UserRound} tone="cyan" /><Stat label="会话数量" value="12" sub="今天更新 3 个" icon={MessageSquare} tone="orange" /><Stat label="文件占用" value="2.4 GB" sub={`${artifacts.length} 个已索引文件`} icon={HardDrive} tone="green" /></div><div className="section-row"><div><div className="section-kicker">实时路由</div><h2 className="section-title">供应商健康度</h2></div><button className="text-btn" onClick={() => setActive('providers')}>查看全部 <ChevronRight size={15} /></button></div><div className="provider-table"><div className="table-head"><span>供应商</span><span>协议</span><span>模型数</span><span>状态</span><span /></div>{providers.map((provider) => <div className="table-row" key={provider.id}><div className="provider-name"><span className={`provider-icon ${provider.accent}`}>{provider.name.slice(0, 1)}</span><strong>{provider.name}</strong></div><span className="muted">{provider.protocol}</span><span>{provider.models}</span><span><Status status={provider.status} /></span><ChevronRight size={16} className="muted" /></div>)}</div></>;
}

function QuickAction({ icon: Icon, label, detail, onClick }: { icon: typeof Zap; label: string; detail: string; onClick: () => void }) { return <button className="quick-action" onClick={onClick}><span className="quick-icon"><Icon size={17} /></span><span><strong>{label}</strong><small>{detail}</small></span><ChevronRight size={15} /></button>; }
function Stat({ label, value, sub, icon: Icon, tone }: { label: string; value: string; sub: string; icon: typeof Zap; tone: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={17} /></div><span className="stat-label">{label}</span><strong>{value}</strong><small>{sub}</small></div>; }
function Status({ status }: { status: string }) { const label = ({ 正常: '正常', 可用: '可用', '需要处理': '需要处理', '冷却中': '冷却中' } as Record<string, string>)[status] || status; return <span className={`status ${status === '正常' || status === '可用' ? 'healthy' : 'warning'}`}><span />{label}</span>; }

function Providers({ providers, setProviders, notify }: { providers: Provider[]; setProviders: (items: Provider[]) => void; notify: (msg: string) => void }) {
  return <><PageHeader eyebrow="控制中心 / 供应商" title="供应商路由" description="统一管理 Responses、Chat Completions、Anthropic 和自定义兼容接口，实时查看能力与健康状态。" action="添加供应商" onAction={() => { setProviders([...providers, { id: `provider-${providers.length + 1}`, name: '新供应商', protocol: 'OpenAI 兼容协议', endpoint: 'https://api.example.com/v1', models: 0, status: '需要处理', accent: 'green' }]); notify('已创建供应商草稿'); }} /><div className="toolbar"><div className="filter-chip active"><ListFilter size={14} />全部供应商</div><div className="filter-chip"><Cloud size={14} />OAuth</div><div className="filter-chip"><KeyRound size={14} />API 密钥</div><span className="toolbar-spacer" /><button className="icon-btn"><RefreshCw size={16} /></button></div><div className="provider-grid">{providers.map((provider) => <article className="provider-card" key={provider.id}><div className="card-top"><span className={`provider-icon large ${provider.accent}`}>{provider.name.slice(0, 1)}</span><button className="icon-btn subtle"><MoreHorizontal size={17} /></button></div><h3>{provider.name}</h3><p className="muted">{provider.protocol}</p><div className="endpoint"><span>{provider.endpoint}</span><Check size={14} /></div><div className="provider-card-footer"><span><strong>{provider.models}</strong> 个模型</span><Status status={provider.status} /></div></article>)}<button className="add-card" onClick={() => notify('供应商模板即将开放')}><span><Plus size={19} /></span><strong>浏览供应商模板</strong><small>OpenAI 兼容、Anthropic、Gemini 等</small></button></div><div className="info-banner"><ShieldCheck size={18} /><div><strong>密钥保存在系统钥匙串</strong><p>SQLite 只保存密钥引用；请求日志仅记录路由元数据，不保存提示词和响应。</p></div><ChevronRight size={16} /></div></>;
}

function Pools({ accounts, notify }: { accounts: Account[]; notify: (msg: string) => void }) { return <><PageHeader eyebrow="控制中心 / 账号池" title="账号池" description="分离订阅身份与 API 出口，按健康度、配额和会话粘性路由每一次请求。" action="创建账号池" onAction={() => notify('已创建账号池草稿')} /><div className="pool-summary"><div className="pool-summary-main"><div className="pool-avatars">{accounts.map((account) => <span className={`pool-avatar ${account.color}`} key={account.id}>{account.name.slice(0, 1).toUpperCase()}</span>)}</div><div><h3>默认编码账号池</h3><p>配额感知 · 会话粘性 · 最多重试 3 次</p></div></div><div className="pool-summary-stat"><span>可用配额</span><strong>67%</strong><small>按 3 个账号加权</small></div><button className="primary-btn compact" onClick={() => notify('账号池路由测试通过')}><Activity size={15} />测试路由</button></div><div className="section-row"><div><div className="section-kicker">池内成员</div><h2 className="section-title">凭据与健康状态</h2></div><div className="route-policy"><span className="online-dot" />配额感知 <ChevronRight size={13} /></div></div><div className="account-list">{accounts.map((account, index) => <div className="account-row" key={account.id}><div className={`account-avatar ${account.color}`}>{account.name.slice(0, 1).toUpperCase()}</div><div className="account-info"><strong>{account.name}</strong><span>{account.provider} · {account.plan}</span></div><div className="quota"><div className="quota-label"><span>剩余配额</span><strong>{account.quota}%</strong></div><div className="quota-track"><span style={{ width: `${account.quota}%` }} className={account.quota < 40 ? 'low' : ''} /></div></div><Status status={account.status} /><button className="icon-btn subtle" onClick={() => notify(`已打开 ${account.name}`)}><MoreHorizontal size={17} /></button></div>)}</div><div className="two-col"><div className="mini-card"><div className="section-kicker">模型命名空间</div><div className="namespace"><code>openrouter/</code><span>deepseek-v4, qwen3-coder</span><Check size={15} /></div><div className="namespace"><code>anthropic/</code><span>claude-sonnet-4.5</span><Check size={15} /></div></div><div className="mini-card"><div className="section-kicker">会话粘性</div><div className="affinity"><LockKeyhole size={19} /><div><strong>会话固定账号</strong><span>TTL 30 分钟 · 生图任务绕过会话粘性</span></div><div className="toggle on"><span /></div></div></div></div></>; }

function Conversations({ notify }: { notify: (msg: string) => void }) { const rows = [['品牌探索', 'OpenRouter · deepseek-v4', '4 分钟前', '1.2 GB'], ['供应商基准测试', 'Codex 订阅 · gpt-5', '18 分钟前', '684 MB'], ['工作区重构', 'Anthropic · claude-sonnet', '昨天', '92 KB'], ['落地页设计', 'OpenRouter · qwen3-coder', '10月6日', '421 MB']]; return <><PageHeader eyebrow="工作区 / 历史会话" title="历史会话" description="搜索、恢复和归档 Codex 会话，同时查看每个会话产生的文件。" action="打开 Codex" onAction={() => notify('已请求 Codex app-server 接管')} /><div className="toolbar"><div className="search inline"><Search size={15} /><input placeholder="搜索会话" /></div><div className="filter-chip active">全部</div><div className="filter-chip">已收藏</div><div className="filter-chip">已归档</div></div><div className="conversation-list">{rows.map(([title, route, time, size]) => <div className="conversation-row" key={title}><div className="conversation-symbol"><MessageSquare size={17} /></div><div className="conversation-info"><strong>{title}</strong><span>{route}</span></div><span className="conversation-time">{time}</span><span className="conversation-size"><HardDrive size={13} />{size}</span><button className="icon-btn subtle" onClick={() => notify(`正在恢复 ${title}`)}><ArrowUpRight size={16} /></button><button className="icon-btn subtle" onClick={() => notify('会话已归档')}><Archive size={16} /></button></div>)}</div></>; }

function Storage({ artifacts, storageTotal, toggleArtifact, quarantineSelected, notify }: { artifacts: Artifact[]; storageTotal: string; toggleArtifact: (id: string) => void; quarantineSelected: () => void; notify: (msg: string) => void }) { const allSelected = artifacts.length > 0 && artifacts.every((item) => item.selected); return <><PageHeader eyebrow="工作区 / 文件清理" title="生成文件" description="删除 Codex 会话不会删除文件。查看文件来源，安全释放空间，也可随时恢复。" action="立即扫描" onAction={() => notify('工作区扫描完成')} /><div className="storage-banner"><div className="storage-ring"><span>2.4</span><small>GB 已占用</small></div><div><div className="section-kicker">可恢复空间</div><h3>Codex 产生的文件</h3><p>{artifacts.length} 个文件，来自 4 个会话 · 上次扫描：2 分钟前</p></div><div className="storage-actions"><button className="secondary-btn" onClick={() => notify('隔离区为空')}><Archive size={15} />打开隔离区</button><button className="primary-btn" onClick={quarantineSelected}><Trash2 size={15} />隔离所选文件</button></div></div><div className="toolbar"><div className="filter-chip active"><FolderOpen size={14} />全部文件</div><div className="filter-chip"><Image size={14} />图片</div><div className="filter-chip"><Database size={14} />数据</div><span className="toolbar-spacer" /><span className="muted">{storageTotal}</span></div><div className="artifact-list"><div className="table-head artifact-head"><label className="check-wrap"><input type="checkbox" checked={allSelected} onChange={() => artifacts.forEach((item) => { if (item.selected !== !allSelected) toggleArtifact(item.id); })} /><span /></label><span>文件</span><span>会话</span><span>大小</span><span>操作</span></div>{artifacts.map((artifact) => <div className="table-row artifact-row" key={artifact.id}><label className="check-wrap"><input type="checkbox" checked={artifact.selected} onChange={() => toggleArtifact(artifact.id)} /><span /></label><div className="artifact-name"><span className="file-icon"><Image size={15} /></span><div><strong>{artifact.name}</strong><small>{artifact.path}</small></div></div><span className="muted">{artifact.session}</span><strong>{artifact.size}</strong><button className="text-btn danger" onClick={() => { toggleArtifact(artifact.id); notify(`${artifact.name} 已选择`); }}><Trash2 size={15} />移除</button></div>)}</div></>; }

function ImageLab({ notify }: { notify: (msg: string) => void }) { return <><PageHeader eyebrow="控制中心 / 生图工作台" title="生图" description="使用已配置的供应商模型生图；当 Codex 无法提供 image_gen 时自动切换 MCP。" action="配置生图账号池" onAction={() => notify('已打开生图账号池设置')} /><div className="image-lab-grid"><div className="image-compose"><div className="compose-head"><div><div className="section-kicker">新建生图任务</div><h3>描述你想生成的内容</h3></div><span className="pill"><span className="pulse" />原生路由就绪</span></div><textarea placeholder="蓝调时刻，一个安静开发者工作区的电影感编辑插画……" /><div className="compose-options"><div className="select-like"><Sparkles size={15} /><span>openrouter/flux-1.1-pro</span><ChevronRight size={14} /></div><div className="select-like"><Image size={15} /><span>1024 × 1024</span><ChevronRight size={14} /></div><button className="primary-btn" onClick={() => notify('生图任务已进入账号池队列')}><Sparkles size={15} />生成</button></div></div><div className="image-side"><div className="section-kicker">生图账号池</div><h3>1 个执行中 · 2 个可用</h3><div className="image-account"><span className="account-avatar cyan">O</span><div><strong>OpenRouter 生图</strong><span>flux-1.1-pro · 0/1 个任务</span></div><Status status="可用" /></div><div className="image-account"><span className="account-avatar violet">C</span><div><strong>Codex 订阅账号</strong><span>原生 image_gen · 0/1 个任务</span></div><Status status="可用" /></div><div className="mcp-fallback"><PlugZap size={17} /><div><strong>MCP 回退已启用</strong><span>原生注入不可用时自动注册 codex-nexus-image。</span></div><Check size={16} /></div></div></div><div className="info-banner"><Gauge size={18} /><div><strong>生图任务独立调度</strong><p>账号池优先选择当前任务最少的账号，本地排队，只记录路由元数据。</p></div></div></>; }

function ExtensionPage({ kind, icon: Icon, accent, notify }: { kind: string; icon: typeof Zap; accent: string; notify: (msg: string) => void }) { const isSkills = kind === 'Skills'; const title = isSkills ? '技能' : '提示词'; const rows = isSkills ? [['code-review', '结合仓库上下文检查代码差异', '全局', '已启用'], ['browser-research', '结构化调研并保留来源笔记', '项目', '已启用'], ['release-notes', '将提交整理为发布说明', '全局', '已停用']] : [['架构决策', '写一份简洁的架构决策记录', '使用 12 次', '收藏'], ['供应商故障', '总结一次路由故障', '使用 5 次', '收藏'], ['生图简报', '把视觉想法整理成可执行提示词', '使用 3 次', '草稿']]; return <><PageHeader eyebrow={`扩展能力 / ${title}`} title={title} description={isSkills ? '管理可复用的 Codex 技能，查看版本并限定适用工作区。' : '管理可复用的提示词，支持变量、标签和项目级覆盖。'} action={isSkills ? '添加技能' : '添加提示词'} onAction={() => notify(isSkills ? '已创建技能草稿' : '已创建提示词草稿')} /><div className="toolbar"><div className="search inline"><Search size={15} /><input placeholder={isSkills ? '搜索技能' : '搜索提示词'} /></div><div className="filter-chip active">全部</div><span className="toolbar-spacer" /><button className="secondary-btn" onClick={() => notify(`已打开${title}导入`)}><Package size={15} />导入</button></div><div className="extension-list">{rows.map(([name, description, scope, status]) => <div className="extension-row" key={name}><div className={`extension-icon ${accent}`}><Icon size={17} /></div><div className="extension-info"><strong>{name}</strong><span>{description}</span></div><span className="scope">{scope}</span><span className={`extension-status ${status === '已启用' || status === '收藏' ? 'active' : ''}`}>{status}</span><button className="icon-btn subtle" onClick={() => notify(`已打开 ${name}`)}><MoreHorizontal size={17} /></button></div>)}</div></>; }

function McpPage({ notify }: { notify: (msg: string) => void }) { return <><PageHeader eyebrow="扩展能力 / MCP 服务" title="MCP 服务" description="连接本地和 Streamable HTTP 工具，明确显示状态、权限和密钥引用。" action="添加 MCP 服务" onAction={() => notify('已创建 MCP 服务草稿')} /><div className="mcp-grid"><McpCard name="codex-nexus-image" kind="STDIO" command="packages/image-mcp/server.mjs" status="已连接" icon={Image} onClick={() => notify('生图 MCP 健康检查通过')} /><McpCard name="codex-app-tools" kind="STDIO" command="由 Codex 应用管理" status="已连接" icon={Code2} onClick={() => notify('Codex App Tools 由宿主管理')} /><McpCard name="browser-research" kind="HTTP" command="http://127.0.0.1:9234/mcp" status="需要处理" icon={Cloud} onClick={() => notify('已打开连接诊断')} /><button className="add-card" onClick={() => notify('MCP 模板即将开放')}><span><Plus size={19} /></span><strong>添加服务</strong><small>STDIO 或 Streamable HTTP</small></button></div><div className="info-banner"><LockKeyhole size={18} /><div><strong>环境变量使用密钥引用</strong><p>MCP 进程只接收 manifest 声明的变量；实际值保存在系统钥匙串，不会出现在诊断信息中。</p></div></div></>; }
function McpCard({ name, kind, command, status, icon: Icon, onClick }: { name: string; kind: string; command: string; status: string; icon: typeof Zap; onClick: () => void }) { return <article className="mcp-card"><div className="card-top"><div className="mcp-icon"><Icon size={18} /></div><span className={`status ${status === '已连接' ? 'healthy' : 'warning'}`}><span />{status}</span></div><h3>{name}</h3><p className="muted">{kind} · {command}</p><button className="text-btn" onClick={onClick}>运行诊断 <ArrowUpRight size={14} /></button></article>; }

function SettingsPage({ notify }: { notify: (msg: string) => void }) { return <><PageHeader eyebrow="工作区 / 设置" title="设置" description="管理本地数据、网关行为、外观和 Codex 运行时集成。" /><div className="settings-grid"><div className="settings-card"><div className="section-kicker">网关</div><SettingRow icon={Waypoints} title="本机回环网关" description="127.0.0.1 · 端口 8787" control={<span className="status healthy"><span />运行中</span>} /><SettingRow icon={KeyRound} title="客户端 API 密钥" description="已在本机生成 · 已隐藏" control={<button className="text-btn" onClick={() => notify('已生成新的本机 API 密钥')}>轮换 <RefreshCw size={14} /></button>} /><SettingRow icon={ShieldCheck} title="仅记录元数据" description="不会保存提示词和响应" control={<div className="toggle on"><span /></div>} /></div><div className="settings-card"><div className="section-kicker">外观</div><SettingRow icon={Sparkles} title="主题" description="深色 · Codex 风格" control={<span className="select-small">深色 <ChevronRight size={13} /></span>} /><SettingRow icon={Activity} title="减少动效" description="跟随系统设置" control={<div className="toggle on"><span /></div>} /><SettingRow icon={FolderOpen} title="数据目录" description="~/Library/Application Support/Codex Nexus" control={<button className="icon-btn subtle" onClick={() => notify('数据目录已复制')}><ArrowUpRight size={15} /></button>} /></div></div></>; }
function SettingRow({ icon: Icon, title, description, control }: { icon: typeof Zap; title: string; description: string; control: ReactNode }) { return <div className="setting-row"><span className="setting-icon"><Icon size={16} /></span><div><strong>{title}</strong><span>{description}</span></div><div className="setting-control">{control}</div></div>; }

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
